services:
  xiangshan-bootcamp:
    image: ghcr.io/openxiangshan/bootcamp:tutorial
    container_name: xiangshan-bootcamp
    networks:
      - bootcamp-br
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      # TODO: remember define these in .env file
      - PASSWORD
      - SUDO_PASSWORD_HASH
      - JUPYTER_PASSWORD_HASH
    volumes:
      - config:/config
      # NOTE: mount workspace as read-only
      # NOTE: user should use tutorial_start.sh to create a writable copy
      - ..:/config/workspace:ro
      # tutorial_start.sh
      - ./data:/data
    restart: unless-stopped

  caddy:
    image: caddy:latest
    container_name: caddy
    ports:
      - 80:80
      - 443:443
    networks:
      - bootcamp-br
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy-config:/config
      - caddy-data:/data

networks:
  bootcamp-br:

volumes:
  config:
  caddy-config:
  caddy-data:
