services:
  xiangshan-bootcamp:
    image: ghcr.io/openxiangshan/bootcamp:tutorial
    container_name: xiangshan-bootcamp
    network_mode: host
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      # - PASSWORD=password #optional
      # - HASHED_PASSWORD= #optional
      - SUDO_PASSWORD=password #optional
      # - SUDO_PASSWORD_HASH= #optional
      # - PROXY_DOMAIN=code-server.my.domain #optional
      # - DEFAULT_WORKSPACE=/config/workspace #optional
      # - PWA_APPNAME=code-server #optional
    volumes:
      - config:/config
      - ..:/config/workspace # mount parent directory to workspace
    ports:
      - 8443:8443 # code-server
      - 8888:8888 # jupyterlab
    restart: unless-stopped

volumes:
  config:
