#!/usr/bin/with-contenv bash
# shellcheck shell=bash

# create new demo user for jupyterlab
useradd -d /config/demo -g abc -G users demo

mkdir -p /config/.local/share/jupyter
chown abc:abc -R /config/.local
find /config/.local -type d -exec chmod g+rwx {} +
find /config/.local -type f -exec chmod g+rw {} +

mkdir -p /config/.cache
chown abc:abc -R /config/.cache
find /config/.cache -type d -exec chmod g+rwx {} +
find /config/.cache -type f -exec chmod g+rw {} +

mkdir -p /config/.config
chown abc:abc -R /config/.config
find /config/.config -type d -exec chmod g+rwx {} +
find /config/.config -type f -exec chmod g+rw {} +

mkdir -p /config/.ipython
chown abc:abc -R /config/.ipython
find /config/.ipython -type d -exec chmod g+rwx {} +
find /config/.ipython -type f -exec chmod g+rw {} +

mkdir -p /config/.jupyter
chown demo:abc -R /config/.jupyter

mkdir -p /data
chown abc:abc /data

SOURCE="/config/workspace"
DEST="/config/demo"

if [ ! -d "${DEST}" ]; then
    mkdir -p "${DEST}"

    EXCLUDE=(
        "assets"
        "tutorial"
        "work"
    )
    declare -A EXCLUDE_MAP=()
    for ex in "${EXCLUDE[@]}"; do
        EXCLUDE_MAP["$ex"]=1
    done

    for entry in "$SOURCE"/*; do
        [ -e "$entry" ] || continue

        name="$(basename "$entry")"

        if [[ -n "${EXCLUDE_MAP[$name]:-}" ]]; then
            continue
        fi

        cp -a --reflink=auto "$entry" "$DEST/"
    done

    cp -a --reflink=auto "$SOURCE/.git" "$DEST/"

    find "$SOURCE/tutorial/" -maxdepth 1 -type f -name "*.ipynb" | while read -r notebook; do
        cp -a --reflink=auto "$notebook" "$DEST/"
    done

    ln -s "$SOURCE/assets" "$DEST/assets"
fi
chown demo:abc -R "${DEST}"
chmod 755 "${DEST}"

rm -f /config/demo/.jupyter/jupyter_lab_config.py

sudo -u demo \
    jupyter-lab --generate-config

# allow remote access
echo "c.ServerApp.ip = '0.0.0.0'" >> /config/demo/.jupyter/jupyter_lab_config.py
echo "c.ServerApp.open_browser = False" >> /config/demo/.jupyter/jupyter_lab_config.py
echo "c.ServerApp.port = 8888" >> /config/demo/.jupyter/jupyter_lab_config.py
echo "c.ServerApp.allow_remote_access = True" >> /config/demo/.jupyter/jupyter_lab_config.py

# set password if provided
if [ -n "${JUPYTER_PASSWORD_HASH}" ]; then
    echo "c.PasswordIdentityProvider.hashed_password = u'${JUPYTER_PASSWORD_HASH}'" >> /config/demo/.jupyter/jupyter_lab_config.py
fi
